# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_split.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_split.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11model_split.proto\"E\n\rPartitionInfo\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x16\n\x0etensor_content\x18\x02 \x01(\x0c\x12\n\n\x02\x63p\x18\x03 \x01(\x05\"5\n\rForwardResult\x12\x16\n\x0etensor_content\x18\x01 \x01(\x0c\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32\x35\n\x05Infer\x12,\n\ninfer_part\x12\x0e.PartitionInfo\x1a\x0e.ForwardResultb\x06proto3'
)




_PARTITIONINFO = _descriptor.Descriptor(
  name='PartitionInfo',
  full_name='PartitionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='PartitionInfo.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tensor_content', full_name='PartitionInfo.tensor_content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cp', full_name='PartitionInfo.cp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=90,
)


_FORWARDRESULT = _descriptor.Descriptor(
  name='ForwardResult',
  full_name='ForwardResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_content', full_name='ForwardResult.tensor_content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ForwardResult.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['PartitionInfo'] = _PARTITIONINFO
DESCRIPTOR.message_types_by_name['ForwardResult'] = _FORWARDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PartitionInfo = _reflection.GeneratedProtocolMessageType('PartitionInfo', (_message.Message,), {
  'DESCRIPTOR' : _PARTITIONINFO,
  '__module__' : 'model_split_pb2'
  # @@protoc_insertion_point(class_scope:PartitionInfo)
  })
_sym_db.RegisterMessage(PartitionInfo)

ForwardResult = _reflection.GeneratedProtocolMessageType('ForwardResult', (_message.Message,), {
  'DESCRIPTOR' : _FORWARDRESULT,
  '__module__' : 'model_split_pb2'
  # @@protoc_insertion_point(class_scope:ForwardResult)
  })
_sym_db.RegisterMessage(ForwardResult)



_INFER = _descriptor.ServiceDescriptor(
  name='Infer',
  full_name='Infer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=147,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='infer_part',
    full_name='Infer.infer_part',
    index=0,
    containing_service=None,
    input_type=_PARTITIONINFO,
    output_type=_FORWARDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INFER)

DESCRIPTOR.services_by_name['Infer'] = _INFER

# @@protoc_insertion_point(module_scope)
