# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_split_pb2 as model__split__pb2


class InferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer_part = channel.unary_unary(
                '/Infer/infer_part',
                request_serializer=model__split__pb2.PartitionInfo.SerializeToString,
                response_deserializer=model__split__pb2.ForwardResult.FromString,
                )


class InferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer_part(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer_part': grpc.unary_unary_rpc_method_handler(
                    servicer.infer_part,
                    request_deserializer=model__split__pb2.PartitionInfo.FromString,
                    response_serializer=model__split__pb2.ForwardResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Infer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Infer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer_part(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Infer/infer_part',
            model__split__pb2.PartitionInfo.SerializeToString,
            model__split__pb2.ForwardResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
